=== daggers-and-sorcery/daggers-and-sorcery-backend/src/main/resources/data/item/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.swordsandsorcery.com/item"
           xmlns="http://www.swordsandsorcery.com/item" elementFormDefault="qualified">
    <xs:element name="item">
        <xs:complexType>
            <xs:all>
                <xs:element name="id" type="xs:unsignedInt" minOccurs="1"/>
                <xs:element name="name" type="xs:string" minOccurs="1"/>
                <xs:element name="type" minOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="ONE_HANDED_SWORD"/>
                            <xs:enumeration value="SHIELD"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="weight" type="xs:unsignedInt"/>
                <xs:element name="modifiers">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="modifier" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="target" minOccurs="1" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="ATTACK"/>
                                                    <xs:enumeration value="DEFENSE"/>
                                                    <xs:enumeration value="INITIATION"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="value" type="xs:integer" minOccurs="1" maxOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== daggers-and-sorcery/daggers-and-sorcery-backend/src/main/resources/data/item/definition/2.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://www.swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.swordsandsorcery.com/item ../schema.xsd">
    <item:id>2</item:id>
    <item:name>Laxi's epic 2</item:name>
    <item:type>ONE_HANDED_SWORD</item:type>
    <item:weight>5</item:weight>
    <item:modifiers>
        <item:modifier>
            <item:target>ATTACK</item:target>
            <item:value>1</item:value>
        </item:modifier>
        <item:modifier>
            <item:target>DEFENSE</item:target>
            <item:value>1</item:value>
        </item:modifier>
    </item:modifiers>
</item:item>

=== daggers-and-sorcery/daggers-and-sorcery-backend/src/main/resources/data/item/definition/0.xml
<?xml version="1.0" encoding="UTF-8"?>

<item:item xmlns:item="http://swordsandsorcery.com/item" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://swordsandsorcery.com/item /data/item/schema.xsd">
    <item:id>0</item:id>
    <item:name>Laxi's epic</item:name>
    <item:type>GENERAL</item:type>
    <item:weight>5</item:weight>
    <item:modifiers>
        <item:modifier>
            <item:target>ATTACK</item:target>
            <item:value>1</item:value>
        </item:modifier>
        <item:modifier>
            <item:target>DEFENSE</item:target>
            <item:value>1</item:value>
        </item:modifier>
    </item:modifiers>
</item:item>
