=== daggers-and-sorcery/daggers-and-sorcery-backend/src/main/resources/data/money/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.swordsandsorcery.com/money"
           xmlns="http://www.swordsandsorcery.com/money" elementFormDefault="qualified">
    <xs:element name="money">
        <xs:complexType>
            <xs:all>
                <xs:element name="id">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="MONEY"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="conversion-list">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="conversion" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="target-id" type="xs:unsignedInt"/>
                                        <xs:element name="conversion-rate" type="xs:unsignedInt"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== daggers-and-sorcery/daggers-and-sorcery-backend/classes/production/swords-money/data/money/definition/money.xml
<?xml version="1.0" encoding="UTF-8"?>

<money:money xmlns:money="http://www.swordsandsorcery.com/money"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.swordsandsorcery.com/money ../schema.xsd">
    <money:id>MONEY</money:id>
    <money:conversion-list>
        <money:conversion>
            <money:target-id>1</money:target-id>
            <money:conversion-rate>1</money:conversion-rate>
        </money:conversion>
        <money:conversion>
            <money:target-id>49</money:target-id>
            <money:conversion-rate>100</money:conversion-rate>
        </money:conversion>
        <money:conversion>
            <money:target-id>50</money:target-id>
            <money:conversion-rate>10000</money:conversion-rate>
        </money:conversion>
        <money:conversion>
            <money:target-id>51</money:target-id>
            <money:conversion-rate>1000000</money:conversion-rate>
        </money:conversion>
    </money:conversion-list>
</money:money>
